## Statistics != Data Science

    It's a tool of data scientists
    
    We are working with experiemental probability, not theoretical
    
    You HAVE to be able to imagine the dataset you need to solve the problem
    before you figure out how to code it in Python.


In [52]:
# interactive matplotlib plots
%matplotlib notebook
import numpy as np
import pandas as pd

#import viz # curriculum example visualizations

np.random.seed(123)

## Generating Random Numbers with Numpy


The numpy.random module provides a number of functions for generating random numbers.

    np.random.choice: selects random options from a list

    np.random.uniform: generates numbers between a given lower and upper bound

    np.random.random: generates numbers between 0 and 1

    np.random.randn: generates numbers from the standard normal distribution

    np.random.normal: generates numbers from a normal distribution with a specified mean and standard deviation

In [53]:
# choice(array, size=None, replace=True, p=None)
np.random.choice([1, 2, 3, 4], (3, 10))

array([[3, 2, 3, 3, 1, 3, 3, 2, 4, 3],
       [4, 2, 3, 2, 1, 2, 3, 4, 2, 1],
       [3, 1, 4, 2, 4, 3, 2, 1, 1, 1]])

In [54]:
#
np.random.uniform(10, 20, (4, 4))

array([[17.37995406, 11.8249173 , 11.75451756, 15.31551374],
       [15.31827587, 16.34400959, 18.49431794, 17.24455325],
       [16.11023511, 17.22443383, 13.22958914, 13.61788656],
       [12.28263231, 12.93714046, 16.30976124, 10.9210494 ]])

In [55]:
#
np.random.random((4,4))

array([[0.43370117, 0.43086276, 0.4936851 , 0.42583029],
       [0.31226122, 0.42635131, 0.89338916, 0.94416002],
       [0.50183668, 0.62395295, 0.1156184 , 0.31728548],
       [0.41482621, 0.86630916, 0.25045537, 0.48303426]])

In [56]:
# numbers from standard normal dist
np.random.randn(10,3)

array([[ 0.01353855,  0.33737412, -0.92662298],
       [ 0.27574741,  0.37085233,  1.17430715],
       [-2.03229248,  0.58250829, -0.7211758 ],
       [-1.7024236 ,  0.76764147,  0.37067905],
       [ 2.07545935,  0.12775769,  1.79988945],
       [ 1.23836635,  0.91375695,  0.46626803],
       [ 0.12503966, -0.19765092, -0.72803492],
       [-0.61031342, -0.87304897,  0.15646903],
       [ 0.28655207,  0.8677178 ,  1.26751791],
       [ 2.10783998, -0.23608945, -0.23208183]])

In [57]:
# takes in mean and std and size
np.random.normal(10, 3, (2, 2))

array([[ 6.76558177, 13.48955361],
       [11.56747022, 15.53309564]])

### Example Problems

#### Carnival Dice Rolls
    You are at a carnival and come across a person in a booth offering you a game of "chance" (as people in booths at carnivals tend to do).

    You pay 5 dollars and roll 3 dice. If the sum of the dice rolls is greater than 12, you get 15 dollars. If it's less than or equal to 12, you get nothing.

    Assuming the dice are fair, should you play this game? How would this change if the winning condition was a sum greater than or equal to 12?

#### The point is to write code that simulates this experiement

In [58]:
ntrials = nrows = 4
n_dice_rolled = ncols = 3
# rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls = np.random.choice([1, 2, 3, 4, 5,6], (ntrials, n_dice_rolled))
rolls


array([[4, 5, 6],
       [5, 2, 5],
       [5, 4, 5],
       [4, 1, 6]])

In [59]:
# default is to sum the whole thing
# axis=0 or axis=1
rolls.sum(axis=1)

array([15, 12, 14, 11])

In [60]:
# creates bool for win or loss
rolls.sum(axis=1) > 12

array([ True, False,  True, False])

In [61]:
# You can do this without .astype(int) and numpy will convert it for you
# probability of winning
p_win = (rolls.sum(axis=1) > 12).mean()

In [62]:
amount_we_win = 15
cost = 5

expected_winnings = p_win * amount_we_win

profit = expected_winnings - cost
profit

2.5

### No Rest or Relaxation


In [63]:
p_nap = .3
naps = np.random.random((10, 2)) <= p_nap
naps

array([[False,  True],
       [ True, False],
       [ True, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False,  True],
       [ True, False],
       [False, False],
       [False, False]])

In [64]:
naps.sum(axis=1)

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 0])

In [65]:
(naps.sum(axis=1) >= 1)

array([ True,  True,  True, False,  True,  True,  True,  True, False,
       False])

In [66]:
# probability of one nap in a weekend
(naps.sum(axis=1) >= 1).mean()

0.7

In [67]:
# probability of zero naps taken in a weekend
(naps.sum(axis=1) == 0).mean()

0.3

### One With Dataframes

    What is the probability of getting at least one 3 in 3 dice rolls?

    To simulate this, we'll use a similar strategy to how we modeled the dice rolls in the previous example, but this time, we'll store the results in a pandas dataframe so that we can apply a lambda function that will check to see if one of the rolls was a 3.

In [68]:
n_trials = 5
n_dice_rolled = 3

rolls = np.random.choice([1, 2, 3, 4, 5, 6], (n_trials, n_dice_rolled))
rolls

array([[1, 2, 4],
       [2, 1, 6],
       [2, 3, 6],
       [3, 3, 6],
       [2, 4, 3]])

In [69]:
df = pd.DataFrame(rolls)
df

0  1  2
0  1  2  4
1  2  1  6
2  2  3  6
3  3  3  6
4  2  4  3

In [70]:
# We need to apply a function row by row which returns
# True or False for 3 in the row
# .values is a Pandas Series
df.apply(lambda row: 3 in row.values, axis=1)

0    False
1    False
2     True
3     True
4     True
dtype: bool

In [71]:
# converts above to probability
df.apply(lambda row: 3 in row.values, axis=1).mean()

0.6

#### Explanation of lambda parts above

In [72]:
s = pd.Series([3, 2, 2])
s

0    3
1    2
2    2
dtype: int64

In [73]:
# converts this to a Numpy array
s.values

array([3, 2, 2])

In [74]:
3 in s.values

True

## Exercises

1. How likely is it that you roll doubles when rolling two dice?



In [75]:
n_trials = nrows = 100
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[4, 2],
       [2, 4],
       [4, 3],
       [5, 1],
       [4, 3],
       [4, 6],
       [3, 3],
       [4, 2],
       [4, 2],
       [4, 4],
       [4, 6],
       [4, 1],
       [1, 5],
       [5, 6],
       [1, 1],
       [5, 2],
       [3, 6],
       [2, 6],
       [5, 2],
       [4, 5],
       [3, 3],
       [5, 4],
       [1, 4],
       [4, 3],
       [6, 2],
       [6, 2],
       [2, 3],
       [3, 6],
       [3, 1],
       [6, 1],
       [2, 4],
       [4, 4],
       [2, 4],
       [2, 3],
       [5, 6],
       [2, 1],
       [2, 5],
       [3, 1],
       [6, 2],
       [3, 5],
       [5, 5],
       [4, 4],
       [2, 5],
       [6, 1],
       [6, 5],
       [6, 1],
       [1, 1],
       [2, 1],
       [5, 4],
       [3, 6],
       [5, 6],
       [1, 2],
       [3, 3],
       [3, 3],
       [4, 3],
       [2, 1],
       [5, 2],
       [6, 6],
       [2, 3],
       [1, 4],
       [2, 4],
       [6, 4],
       [6, 4],
       [6, 2],
       [6, 2],
       [2, 4],
       [6,

In [13]:
# function to create a bool list returning True for doubles rolled
def doubles_trial(rolls):
    return [roll[0] == roll[1] for roll in rolls]
doubles_trial(rolls)

[False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False]

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

 

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

5. Compare Heights

    Men have an average height of 178 cm and standard deviation of 8cm.
    
    Women have a mean of 170, sd = 6cm.
    
    If a man and woman are chosen at random, P(woman taller than man)?

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?



8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?